### ISSUE TITLE
AI7688 Board Booting issue

### ISSUE THREAD

**Issue by dhawallad** [AcSiP/AI7688H#2]
Hi,

I need to update the firmware in AI7688 module over serial.

Can you please provide me the steps to update the firmware over serial using loadb command.

Thanks,
Lad Dhawal Umesh

**Comment by Ritesh236** [comment]
Hello Team,

Myself Ritesh Prajapati working with Dhawal into same project

Here, We are struggling to flash kernel image or sysfsupgrade image from Boot Loader itself in which we are using cp.linux command from boot loader which has been already flashed by module manufacture using below link

[GitHub - AcSiP/linkit-smart-7688-uboot at AI7688H__64MB](https://github.com/AcSiP/linkit-smart-7688-uboot/tree/AI7688H__64MB)

So, We just need one help regarding actual load address and flash address using which we can able to flash images using cp.linux command as flash is already erased except u-boot partition?

We have checked cp.linux command source code into boot loader but didn;t get exact address location from where it is going to copy image from RAM location to Flash Location. SO It would be good if you can provide some help for the understanding.

Let me know if need anything else from my end to understand issue

Regards,
Ritesh Prajapati

**Comment by Ritesh236** [comment]
Hello Team,

We have checked and it seems like cp.linux is not working but we found option after reset from where able to flash boot loader and sysupgrade image into flash memory

Regards,
Ritesh Prajapati

**Comment by dhawallad** [comment]
We have checked into boot loader source and found that there is option 0 available but not shown into choose options

File Name - (https://github.com/AcSiP/linkit-smart-7688-uboot/blob/AI7688H__64MB/lib_mips/board.c)

`#define SEL_LOAD_LINUX_WRITE_FLASH_BY_SERIAL 0
#define SEL_LOAD_LINUX_SDRAM 1
#define SEL_LOAD_LINUX_WRITE_FLASH 2
#define SEL_BOOT_FLASH 3
#define SEL_ENTER_CLI 4
#define SEL_LOAD_BOOT_WRITE_FLASH_BY_SERIAL 7
#define SEL_LOAD_BOOT_SDRAM 8
#define SEL_LOAD_BOOT_WRITE_FLASH 9

void OperationSelect(void)
{
printf("\nPlease choose the operation: \n");
printf(" %d: Load system code to SDRAM via TFTP. \n", SEL_LOAD_LINUX_SDRAM);
printf(" %d: Load system code then write to Flash via TFTP. \n", SEL_LOAD_LINUX_WRITE_FLASH);
printf(" %d: Boot system code via Flash (default).\n", SEL_BOOT_FLASH);
#ifdef RALINK_CMDLINE
printf(" %d: Entr boot command line interface.\n", SEL_ENTER_CLI);
#endif // RALINK_CMDLINE //
#ifdef RALINK_UPGRADE_BY_SERIAL
printf(" %d: Load Boot Loader code then write to Flash via Serial. \n", SEL_LOAD_BOOT_WRITE_FLASH_BY_SERIAL);
#endif // RALINK_UPGRADE_BY_SERIAL //
printf(" %d: Load Boot Loader code then write to Flash via TFTP. \n", SEL_LOAD_BOOT_WRITE_FLASH);
}`

As you can see above that there are all options defined for Linux Image write into Flash Memory and Boot Loader Image into Flash Memory

#define SEL_LOAD_LINUX_WRITE_FLASH_BY_SERIAL 0
#define SEL_LOAD_BOOT_WRITE_FLASH_BY_SERIAL 7

So, Above both option will be useful to write boot loader and sysupgrade images into flash memory from boot loader through serial

We got success to flash both boot loader and sysfsupgrade images successfully into flash memory

Let me know if need anything else from my end
